
<?php if(!defined('ABSPATH')) exit;
add_action('admin_menu',function(){ add_menu_page('Kodra žinutės','Kodra žinutės','manage_options','kcf-messages','kcf_admin_messages_page','dashicons-email-alt2',26); add_submenu_page('kcf-messages','Gauti laiškai','Gauti laiškai','manage_options','kcf-inbox','kcf_admin_inbox_page'); add_submenu_page('kcf-messages','Nustatymai','Nustatymai','manage_options','kcf-settings','kcf_admin_settings_page'); add_submenu_page('kcf-messages','Diagnostika','Diagnostika','manage_options','kcf-diagnostics','kcf_admin_diagnostics_page'); });
add_action('admin_post_kcf_delete_message',function(){ if(!current_user_can('manage_options')) wp_die('Unauthorized'); check_admin_referer('kcf_delete_message'); global $wpdb; $id=intval($_GET['id']??0); if($id){ $wpdb->delete(KCF_TABLE,['id'=>$id]); $wpdb->delete(KCF_REPLIES_TABLE,['message_id'=>$id]); } wp_safe_redirect(admin_url('admin.php?page=kcf-messages&deleted=1')); exit; });
add_action('admin_post_kcf_reply_message',function(){ if(!current_user_can('manage_options')) wp_die('Unauthorized'); check_admin_referer('kcf_reply_message'); global $wpdb; $message_id=intval($_POST['message_id']); $row=$wpdb->get_row($wpdb->prepare('SELECT email FROM '.KCF_TABLE.' WHERE id=%d',$message_id)); $to=$row?$row->email:''; $subject=sanitize_text_field(wp_unslash($_POST['subject']??'')); $body_raw=isset($_POST['body'])?wp_unslash($_POST['body']):''; $body=kcf_clean_textarea($body_raw); if($body===''){ $redirect=admin_url('admin.php?page=kcf-messages'.($message_id?('&view='.$message_id):'')); $redirect=add_query_arg('reply_error',1,$redirect); wp_safe_redirect($redirect); exit; } $user_id=get_current_user_id(); $tokens=[]; $headers=['Content-Type: text/html; charset=UTF-8']; if($message_id>0){ $tokens['KCF-ID']=$message_id; $headers[]='X-KCF-ID: '.$message_id; } $body_html=kcf_prepare_email_body($body,$tokens); $sent=wp_mail($to,$subject,$body_html,$headers); $thread_root=$message_id>0?$message_id:0; $wpdb->insert(KCF_REPLIES_TABLE,['message_id'=>$message_id,'thread_root'=>$thread_root,'created_at'=>current_time('mysql'),'wp_user_id'=>$user_id,'direction'=>0,'to_email'=>$to,'subject'=>$subject,'body'=>$body,'sent'=>$sent?1:0,'seen'=>0],['%d','%d','%s','%d','%d','%s','%s','%s','%d','%d']); wp_safe_redirect(admin_url('admin.php?page=kcf-messages&view='.$message_id.'&replied='.($sent?'1':'0'))); exit; });
add_action('admin_post_kcf_delete_inbox',function(){ if(!current_user_can('manage_options')) wp_die('Unauthorized'); check_admin_referer('kcf_delete_inbox'); global $wpdb; $id=intval($_GET['id']??0); if($id){ $wpdb->delete(KCF_REPLIES_TABLE,['id'=>$id,'direction'=>1]); } wp_safe_redirect(admin_url('admin.php?page=kcf-inbox&deleted=1')); exit; });
add_action('admin_post_kcf_bulk_delete_inbox',function(){ if(!current_user_can('manage_options')) wp_die('Unauthorized'); check_admin_referer('kcf_bulk_delete_inbox'); $ids=isset($_POST['ids'])&&is_array($_POST['ids'])?array_map('intval',$_POST['ids']):[]; $ids=array_filter($ids); $redirect=admin_url('admin.php?page=kcf-inbox'); if(!empty($_POST['redirect_to'])){ $maybe=esc_url_raw(wp_unslash($_POST['redirect_to'])); if($maybe){ $redirect=$maybe; } } if(!$ids){ wp_safe_redirect(add_query_arg('bulk_error',1,$redirect)); exit; } global $wpdb; $placeholders=implode(',',array_fill(0,count($ids),'%d')); $sql='DELETE FROM '.KCF_REPLIES_TABLE.' WHERE direction=1 AND id IN ('.$placeholders.')'; $wpdb->query($wpdb->prepare($sql,$ids)); $deleted=intval($wpdb->rows_affected); wp_safe_redirect(add_query_arg('bulk_deleted',$deleted,$redirect)); exit; });
add_action('admin_post_kcf_reply_inbox',function(){ if(!current_user_can('manage_options')) wp_die('Unauthorized'); check_admin_referer('kcf_reply_inbox'); global $wpdb; $inbox_id=intval($_POST['inbox_id']??0); $redirect=admin_url('admin.php?page=kcf-inbox'); if($inbox_id){ $redirect=add_query_arg(['page'=>'kcf-inbox','view'=>$inbox_id],admin_url('admin.php')); } if(!$inbox_id){ wp_safe_redirect(add_query_arg('reply_error',1,$redirect)); exit; } $row=$wpdb->get_row($wpdb->prepare('SELECT to_email,subject,message_id FROM '.KCF_REPLIES_TABLE.' WHERE id=%d AND direction=1',$inbox_id),ARRAY_A); if(!$row){ wp_safe_redirect(add_query_arg('reply_error',1,$redirect)); exit; } $to=sanitize_email($row['to_email']); $subject=sanitize_text_field(wp_unslash($_POST['subject']??'')); $body_raw=isset($_POST['body'])?wp_unslash($_POST['body']):''; $body=kcf_clean_textarea($body_raw); if(!$to||$body===''){ wp_safe_redirect(add_query_arg('reply_error',1,$redirect)); exit; } if($subject===''){ $subject='(be temos)'; } $user_id=get_current_user_id(); $tokens=[]; if(intval($row['message_id'])>0){ $tokens['KCF-ID']=intval($row['message_id']); } $tokens['KCF-INBOX-ID']=$inbox_id; $body_html=kcf_prepare_email_body($body,$tokens); $headers=['Content-Type: text/html; charset=UTF-8','X-KCF-INBOX-ID: '.$inbox_id]; if(!empty($tokens['KCF-ID'])) $headers[]='X-KCF-ID: '.intval($row['message_id']); $sent=wp_mail($to,$subject,$body_html,$headers); $message_id=intval($row['message_id']); $thread_root=$message_id>0?$message_id:$inbox_id; $wpdb->insert(KCF_REPLIES_TABLE,['message_id'=>$message_id,'thread_root'=>$thread_root,'created_at'=>current_time('mysql'),'wp_user_id'=>$user_id,'direction'=>0,'to_email'=>$to,'subject'=>$subject,'body'=>$body,'sent'=>$sent?1:0,'seen'=>1],['%d','%d','%s','%d','%d','%s','%s','%s','%d','%d']); wp_safe_redirect(add_query_arg('replied',$sent?1:0,$redirect)); exit; });
add_action('admin_post_kcf_check_imap_now',function(){ if(!current_user_can('manage_options')) wp_die('Unauthorized'); check_admin_referer('kcf_check_imap_now'); do_action('kcf_check_mail_event'); wp_safe_redirect(admin_url('admin.php?page=kcf-diagnostics')); exit; });
function kcf_mark_message_seen($id){ global $wpdb; $wpdb->update(KCF_TABLE,['seen'=>1],['id'=>$id]); $wpdb->query($wpdb->prepare('UPDATE '.KCF_REPLIES_TABLE.' SET seen=1 WHERE message_id=%d AND seen=0',$id)); }
function kcf_mark_inbox_seen($id){ global $wpdb; $wpdb->update(KCF_REPLIES_TABLE,['seen'=>1],['id'=>$id]); }
function kcf_admin_maybe_check_imap(){ static $done=false; if($done) return; $done=true; do_action('kcf_check_mail_event'); }
function kcf_admin_messages_page(){ if(!current_user_can('manage_options')) return; global $wpdb; $table=KCF_TABLE; $highlight_script='<script>(function(){document.addEventListener("DOMContentLoaded",function(){var highlightEls=document.querySelectorAll(".kcf-highlight");if(!highlightEls.length)return;setTimeout(function(){highlightEls.forEach(function(el){el.classList.add("kcf-fade-end");setTimeout(function(){el.classList.remove("kcf-fade-end");el.classList.remove("kcf-highlight");},800);});},60000);});})();</script>';
  kcf_admin_maybe_check_imap(); echo '<div class="wrap"><h1>Kodra žinutės</h1><style>.kcf-highlight{background:#fff3cd!important;transition:background-color .6s ease;}.kcf-highlight.kcf-fade-end{background:#fff!important;}</style>';
  if(isset($_GET['replied'])){ if(intval($_GET['replied'])===1) echo '<div class="updated notice notice-success is-dismissible"><p>Atsakymas išsiųstas.</p></div>'; else echo '<div class="error notice notice-error"><p>Atsakymo išsiųsti nepavyko.</p></div>'; }
  if(isset($_GET['reply_error'])) echo '<div class="error notice notice-error"><p>Patikrinkite atsakymo laukus.</p></div>';
  $q=sanitize_text_field($_GET['q']??''); echo '<form method="get" style="margin:8px 0 12px"><input type="hidden" name="page" value="kcf-messages"><input type="text" name="q" value="'.esc_attr($q).'" placeholder="Paieška (vardas, paštas, tel., įmonė)" style="min-width:340px;margin-right:6px"><button class="button button-primary">Ieškoti</button> <a class="button" href="'.admin_url('admin.php?page=kcf-messages').'">Išvalyti</a></form>';
  if(isset($_GET['view'])){ $id=intval($_GET['view']); $row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE id=%d",$id),ARRAY_A); echo '<h2>#'.intval($id).'</h2>'; if($row){ echo '<div class="kcf-two-col"><div class="kcf-col kcf-col-left"><h3>Pagrindinė informacija</h3><table class="widefat striped">'; foreach(['Vardas'=>$row['name'],'Telefonas'=>$row['phone'],'El. paštas'=>$row['email'],'Žinutė'=>$row['message']] as $l=>$v){ echo '<tr><th>'.esc_html($l).'</th><td>'.wp_kses_post(nl2br(esc_html((string)$v))).'</td></tr>'; } echo '</table></div><div class="kcf-col kcf-col-right"><h3>Kita</h3><table class="widefat striped">'; foreach(['Data'=>$row['created_at'],'Įmonė'=>$row['company'],'IP adresas'=>$row['ip'],'Naršyklė'=>$row['user_agent'],'Įrašo ID'=>$row['id']] as $l=>$v){ echo '<tr><th>'.esc_html($l).'</th><td>'.wp_kses_post(nl2br(esc_html((string)$v))).'</td></tr>'; } echo '</table></div></div>'; echo '<style>.kcf-two-col{display:grid;grid-template-columns:7fr 3fr;gap:18px;max-width:100%;width:100%}.kcf-two-col th{width:220px}.kcf-two-col th,.kcf-two-col td{word-break:break-word;overflow-wrap:anywhere}.kcf-thread-item.kcf-latest strong{font-weight:500}.kcf-unread-dot{display:inline-block;width:8px;height:8px;background:#d63638;border-radius:50%;margin-left:6px;vertical-align:middle}</style>';
    $delete_url=wp_nonce_url(admin_url('admin-post.php?action=kcf_delete_message&id='.$id),'kcf_delete_message'); echo '<p style="margin-top:12px"><a href="'.$delete_url.'" class="button button-danger kcf-del">Ištrinti</a> <a href="'.admin_url('admin.php?page=kcf-messages').'" class="button">Grįžti</a></p><script>document.addEventListener("click",e=>{if(e.target.classList.contains("kcf-del")&&!confirm("Ar tikrai ištrinti šią žinutę?")){e.preventDefault();}});</script>';
    echo '<hr><h2>Atsakymų gija</h2>'; $replies=$wpdb->get_results($wpdb->prepare("SELECT r.*, u.display_name FROM ".KCF_REPLIES_TABLE." r LEFT JOIN {$wpdb->users} u ON u.ID=r.wp_user_id WHERE r.message_id=%d ORDER BY r.id ASC",$id),ARRAY_A);
    if($replies){ $total=count($replies); $i=0; echo '<ul class="kcf-thread" id="kcf-thread">'; foreach($replies as $rep){ $i++; $by=intval($rep['direction'])===1?'Klientas':(!empty($rep['display_name'])?$rep['display_name']:'Admin'); $cls=intval($rep['seen'])===0?' kcf-unread-burst kcf-highlight':''; if($i===$total){ $cls.=' kcf-latest'; } $clean=function_exists('kcf_trim_body_for_admin')?kcf_trim_body_for_admin($rep['body']):$rep['body']; echo '<li class="kcf-thread-item'.$cls.'"><div><strong>'.esc_html($rep['subject']).'</strong></div><div><em>'.esc_html($rep['created_at']).'</em> — '.esc_html($by).'</div><div style="word-break:break-word">'.wp_kses_post(nl2br(esc_html($clean))).'</div></li>'; } echo '</ul>'.$highlight_script; } else { echo '<p>Gijoje dar nėra įrašų.</p>'; }
    $default_subject='Re: [KCF #'.$id.'] Atsakymas į Jūsų žinutę'; echo '<hr><h2>Atsakyti</h2><form method="post" action="'.admin_url('admin-post.php?action=kcf_reply_message').'" style="max-width:700px">'; wp_nonce_field('kcf_reply_message'); echo '<input type="hidden" name="message_id" value="'.intval($id).'"><input type="hidden" name="to" value=""><p><label>Tema: <input type="text" name="subject" value="'.esc_attr($default_subject).'" style="width:100%" required></label></p><p><label>Žinutė:<br><textarea name="body" rows="8" style="width:100%" required></textarea></label></p><p><button type="submit" class="button button-primary">Siųsti atsakymą</button></p></form>'; kcf_mark_message_seen($id);
  } else { echo '<p>Įrašas nerastas.</p>'; } echo '</div>'; return; }
  $where='WHERE 1=1'; $params=[]; if($q){ $like='%'.$wpdb->esc_like($q).'%'; $where.=' AND (name LIKE %s OR email LIKE %s OR phone LIKE %s OR company LIKE %s)'; $params=[$like,$like,$like,$like]; }
  $per=20; $paged=max(1,intval($_GET['paged']??1)); $off=($paged-1)*$per; $sql_total="SELECT COUNT(*) FROM {$table} $where"; $total=(int)($params? $wpdb->get_var($wpdb->prepare($sql_total,$params)) : $wpdb->get_var($sql_total));
  $sql_items="SELECT id,created_at,name,email,phone,company,LEFT(message,160) AS excerpt, seen FROM {$table} $where ORDER BY id DESC LIMIT %d OFFSET %d"; if($params){ $args=array_merge($params,[$per,$off]); $items=$wpdb->get_results($wpdb->prepare($sql_items,$args),ARRAY_A); } else { $items=$wpdb->get_results($wpdb->prepare($sql_items,$per,$off),ARRAY_A); }
  $base=admin_url('admin.php?page=kcf-messages'); echo '<table class="widefat striped" style="table-layout:fixed"><thead><tr><th style="width:60px">ID</th><th style="width:160px">Data</th><th style="width:140px">Vardas</th><th style="width:220px">El. paštas</th><th style="width:160px">Telefonas</th><th style="width:160px">Įmonė</th><th>Žinutė</th><th style="width:190px">Veiksmai</th></tr></thead><tbody>';
  if($items){ 
    foreach($items as $it){ $view=esc_url(add_query_arg(['view'=>$it['id']],$base)); $del=wp_nonce_url(admin_url('admin-post.php?action=kcf_delete_message&id='.$it['id']),'kcf_delete_message'); $row_cls=intval($it['seen'])===0?' class="kcf-highlight"':''; $dot=intval($it['seen'])===0?' <span class="kcf-unread-dot" title="Neskaityta"></span>':''; echo '<tr'.$row_cls.'><td><a href="'.$view.'">'.intval($it['id']).'</a>'.$dot.'</td><td>'.esc_html($it['created_at']).'</td><td>'.esc_html($it['name']).'</td><td style="word-break:break-word"><a href="mailto:'.esc_attr($it['email']).'">'.esc_html($it['email']).'</a></td><td>'.esc_html($it['phone']).'</td><td>'.esc_html($it['company']).'</td><td style="word-break:break-word">'.esc_html($it['excerpt']).'</td><td><a href="'.$view.'" class="button">Peržiūrėti</a> <a href="'.$del.'" class="button kcf-del">Ištrinti</a></td></tr>'; }
  } else { echo '<tr><td colspan="8">Nėra įrašų.</td></tr>'; }
  echo '</tbody></table>';
  echo '<script>document.addEventListener("click",function(e){if(e.target.classList.contains("kcf-del")&&!confirm("Ar tikrai ištrinti?")){e.preventDefault();}});</script>';
  echo $highlight_script; $pages=max(1,ceil($total/$per)); if($pages>1){ echo '<div class="tablenav"><div class="tablenav-pages">'.paginate_links(['base'=>$base.'%_%','format'=>'&paged=%#%','current'=>$paged,'total'=>$pages]).'</div></div>'; } echo '</div>'; }
function kcf_admin_inbox_page(){ if(!current_user_can('manage_options')) return; global $wpdb; $table=KCF_REPLIES_TABLE; $highlight_script='<script>(function(){document.addEventListener("DOMContentLoaded",function(){var highlightEls=document.querySelectorAll(".kcf-highlight");if(!highlightEls.length)return;setTimeout(function(){highlightEls.forEach(function(el){el.classList.add("kcf-fade-end");setTimeout(function(){el.classList.remove("kcf-fade-end");el.classList.remove("kcf-highlight");},800);});},60000);});})();</script>';
  kcf_admin_maybe_check_imap(); echo '<div class="wrap"><h1>Gauti laiškai</h1><style>.kcf-highlight{background:#fff3cd!important;transition:background-color .6s ease;}.kcf-highlight.kcf-fade-end{background:#fff!important;}.kcf-unread-dot{display:inline-block;width:8px;height:8px;background:#d63638;border-radius:50%;margin-left:6px;vertical-align:middle}</style>';
  if(isset($_GET['deleted'])) echo '<div class="updated notice notice-success is-dismissible"><p>Laiškas ištrintas.</p></div>';
  if(isset($_GET['bulk_deleted'])){ $cnt=max(0,intval($_GET['bulk_deleted'])); if($cnt>1){ $msg=sprintf('%d laiškai ištrinti.',$cnt); } elseif($cnt===1){ $msg='1 laiškas ištrintas.'; } else { $msg='Neištrintas nė vienas laiškas.'; } echo '<div class="updated notice notice-success is-dismissible"><p>'.esc_html($msg).'</p></div>'; }
  if(isset($_GET['bulk_error'])) echo '<div class="error notice notice-error"><p>Pasirinkite bent vieną laišką.</p></div>';
  if(isset($_GET['replied'])){ if(intval($_GET['replied'])===1) echo '<div class="updated notice notice-success is-dismissible"><p>Atsakymas išsiųstas.</p></div>'; else echo '<div class="error notice notice-error"><p>Atsakymo išsiųsti nepavyko.</p></div>'; }
  if(isset($_GET['reply_error'])) echo '<div class="error notice notice-error"><p>Patikrinkite atsakymo laukus.</p></div>';
  $q=sanitize_text_field($_GET['q']??''); echo '<form method="get" style="margin:8px 0 12px"><input type="hidden" name="page" value="kcf-inbox"><input type="text" name="q" value="'.esc_attr($q).'" placeholder="Paieška (tema, siuntėjas, žinutė)" style="min-width:340px;margin-right:6px"><button class="button button-primary">Ieškoti</button> <a class="button" href="'.admin_url('admin.php?page=kcf-inbox').'">Išvalyti</a></form>';
  if(isset($_GET['view'])){ $id=intval($_GET['view']); $sql="SELECT r.*, m.name AS message_name FROM {$table} r LEFT JOIN ".KCF_TABLE." m ON m.id=r.message_id WHERE r.id=%d AND r.direction=1"; $row=$wpdb->get_row($wpdb->prepare($sql,$id),ARRAY_A); echo '<h2>#'.intval($id).'</h2>';
    if($row){ $related='-'; if(intval($row['message_id'])>0){ $link=admin_url('admin.php?page=kcf-messages&view='.$row['message_id']); $label='#'.intval($row['message_id']); if(!empty($row['message_name'])) $label.=' ('.wp_strip_all_tags($row['message_name']).')'; $related='<a href="'.esc_url($link).'">'.esc_html($label).'</a>'; }
      $sender=$row['to_email']!==''?$row['to_email']:'—'; $subject=$row['subject']!==''?$row['subject']:'(be temos)';
      echo '<table class="widefat striped" style="max-width:720px"><tbody><tr><th style="width:180px">Siuntėjas</th><td>'.esc_html($sender).'</td></tr><tr><th>Tema</th><td>'.esc_html($subject).'</td></tr><tr><th>Gauta</th><td>'.esc_html($row['created_at']).'</td></tr><tr><th>Susieta žinutė</th><td>'.$related.'</td></tr></tbody></table>';
      echo '<div style="margin-top:18px"><h3>Žinutė</h3><div style="background:#fff;border:1px solid #ddd;padding:16px;max-width:720px;word-break:break-word">'.nl2br(esc_html($row['body'])).'</div></div>';
      $default_subject=$row['subject']!==''?'Re: '.$row['subject']:'Atsakymas į Jūsų laišką';
      if(intval($row['message_id'])>0){ $needle='[KCF #'.intval($row['message_id']).']'; if(strpos($default_subject,$needle)===false){ $default_subject=$needle.' '.$default_subject; } }
      echo '<hr><h2>Atsakyti</h2><form method="post" action="'.esc_url(admin_url('admin-post.php?action=kcf_reply_inbox')).'" style="max-width:720px">';
      wp_nonce_field('kcf_reply_inbox');
      echo '<input type="hidden" name="inbox_id" value="'.intval($id).'">';
      echo '<p><label>Tema:<br><input type="text" name="subject" value="'.esc_attr($default_subject).'" style="width:100%" required></label></p>';
      echo '<p><label>Žinutė:<br><textarea name="body" rows="8" style="width:100%" required></textarea></label></p>';
      echo '<p><button type="submit" class="button button-primary">Siųsti atsakymą</button></p></form>';
      $delete_url=wp_nonce_url(admin_url('admin-post.php?action=kcf_delete_inbox&id='.$id),'kcf_delete_inbox'); echo '<p style="margin-top:18px"><a href="'.$delete_url.'" class="button button-danger kcf-del">Ištrinti</a> <a href="'.admin_url('admin.php?page=kcf-inbox').'" class="button">Grįžti</a></p><script>document.addEventListener("click",function(e){if(e.target.classList.contains("kcf-del")&&!confirm("Ar tikrai ištrinti šį laišką?")){e.preventDefault();}});</script>';
      kcf_mark_inbox_seen($id);
    } else { echo '<p>Laiškas nerastas.</p>'; }
    echo '</div>';
    return;
  }
  $where='WHERE r.direction=1'; $params=[]; if($q){ $like='%'.$wpdb->esc_like($q).'%'; $where.=' AND (r.subject LIKE %s OR r.to_email LIKE %s OR r.body LIKE %s)'; $params=[$like,$like,$like]; }
  $per=20; $paged=max(1,intval($_GET['paged']??1)); $off=($paged-1)*$per; $sql_total="SELECT COUNT(*) FROM {$table} r $where"; $total=(int)($params? $wpdb->get_var($wpdb->prepare($sql_total,$params)) : $wpdb->get_var($sql_total));
  $sql_items="SELECT r.id,r.created_at,r.subject,r.to_email,r.body,r.seen,r.message_id,m.name AS message_name FROM {$table} r LEFT JOIN ".KCF_TABLE." m ON m.id=r.message_id $where ORDER BY r.id DESC LIMIT %d OFFSET %d";
  if($params){ $args=array_merge($params,[$per,$off]); $items=$wpdb->get_results($wpdb->prepare($sql_items,$args),ARRAY_A); }
  else { $items=$wpdb->get_results($wpdb->prepare($sql_items,$per,$off),ARRAY_A); }
  $base=admin_url('admin.php?page=kcf-inbox'); $current_url=isset($_SERVER['REQUEST_URI'])?esc_url_raw(wp_unslash($_SERVER['REQUEST_URI'])):''; echo '<form method="post" action="'.esc_url(admin_url('admin-post.php')).'" id="kcf-inbox-form">'; echo '<input type="hidden" name="action" value="kcf_bulk_delete_inbox">'; wp_nonce_field('kcf_bulk_delete_inbox'); echo '<input type="hidden" name="redirect_to" value="'.esc_attr($current_url).'">'; echo '<div class="tablenav top"><div class="alignleft actions bulkactions"><button type="submit" class="button kcf-bulk-delete" disabled>Trinti pažymėtus</button></div></div>';
  echo '<table class="widefat striped" style="table-layout:fixed"><thead><tr><td id="cb" class="manage-column column-cb check-column"><input type="checkbox" class="kcf-select-all" aria-label="Pažymėti visus"></td><th style="width:70px">ID</th><th style="width:160px">Data</th><th style="width:220px">Siuntėjas</th><th style="width:220px">Tema</th><th>Žinutė</th><th style="width:200px">Susieta žinutė</th><th style="width:140px">Veiksmai</th></tr></thead><tbody>';
  if($items){ foreach($items as $it){ $view=esc_url(add_query_arg(['view'=>$it['id']],$base)); $del=wp_nonce_url(admin_url('admin-post.php?action=kcf_delete_inbox&id='.$it['id']),'kcf_delete_inbox'); $row_cls=intval($it['seen'])===0?' class="kcf-highlight"':''; $dot=intval($it['seen'])===0?' <span class="kcf-unread-dot" title="Neskaitytas"></span>':''; $raw_body=(string)$it['body']; $excerpt=wp_trim_words($raw_body,30,'…'); $related='-'; if(intval($it['message_id'])>0){ $label='#'.intval($it['message_id']); if(!empty($it['message_name'])) $label.=' ('.wp_strip_all_tags($it['message_name']).')'; $related='<a href="'.esc_url(admin_url('admin.php?page=kcf-messages&view='.$it['message_id'])).'">'.esc_html($label).'</a>'; }
    $sender=$it['to_email']!==''?$it['to_email']:'—'; $subject=$it['subject']!==''?$it['subject']:'(be temos)';
    echo '<tr'.$row_cls.'><th scope="row" class="check-column"><input type="checkbox" class="kcf-row-checkbox" name="ids[]" value="'.intval($it['id']).'" aria-label="Pažymėti laišką #'.intval($it['id']).'"></th><td><a href="'.$view.'">'.intval($it['id']).'</a>'.$dot.'</td><td>'.esc_html($it['created_at']).'</td><td style="word-break:break-word">'.esc_html($sender).'</td><td style="word-break:break-word">'.esc_html($subject).'</td><td style="word-break:break-word">'.esc_html($excerpt).'</td><td>'.$related.'</td><td><a href="'.$view.'" class="button">Peržiūrėti</a> <a href="'.$del.'" class="button kcf-del">Ištrinti</a></td></tr>'; }
  } else { echo '<tr><td colspan="8">Nėra gautų laiškų.</td></tr>'; }
  echo '</tbody></table><div class="tablenav bottom"><div class="alignleft actions bulkactions"><button type="submit" class="button kcf-bulk-delete" disabled>Trinti pažymėtus</button></div></div></form>';
  echo '<script>(function(){document.addEventListener("click",function(e){if(e.target.classList.contains("kcf-del")&&!confirm("Ar tikrai ištrinti?")){e.preventDefault();}});document.addEventListener("DOMContentLoaded",function(){var form=document.getElementById("kcf-inbox-form");if(!form)return;var boxes=Array.prototype.slice.call(form.querySelectorAll(".kcf-row-checkbox"));var master=form.querySelector(".kcf-select-all");var buttons=Array.prototype.slice.call(form.querySelectorAll(".kcf-bulk-delete"));function anyChecked(){return boxes.some(function(cb){return cb.checked;});}function updateButtons(){var active=anyChecked();buttons.forEach(function(btn){btn.disabled=!active;});if(master){var total=boxes.length;var checked=boxes.filter(function(cb){return cb.checked;}).length;master.checked=active&&checked===total;master.indeterminate=checked>0&&checked<total;}}boxes.forEach(function(cb){cb.addEventListener("change",updateButtons);});if(master){master.addEventListener("change",function(){var checked=this.checked;boxes.forEach(function(cb){cb.checked=checked;});updateButtons();});}updateButtons();form.addEventListener("submit",function(e){if(!anyChecked()||!confirm("Ar tikrai ištrinti pažymėtus laiškus?")){e.preventDefault();}});});})();</script>';
  echo $highlight_script; $pages=max(1,ceil($total/$per)); if($pages>1){ echo '<div class="tablenav"><div class="tablenav-pages">'.paginate_links(['base'=>$base.'%_%','format'=>'&paged=%#%','current'=>$paged,'total'=>$pages]).'</div></div>'; }
  echo '</div>';
}
function kcf_admin_diagnostics_page(){ if(!current_user_can('manage_options')) return; $ret_days=intval(kcf_settings_get('log_retention_days',30)); if(isset($_POST['kcf_clear_logs'])&&check_admin_referer('kcf_clear_logs')){ delete_option('kcf_log'); echo '<div class="updated"><p>Logai ištrinti.</p></div>'; } $log=get_option('kcf_log',[]); if($log){ $kept=[]; $cutoff=strtotime('-'.$ret_days.' days'); foreach($log as $line){ $ts=strtotime(substr($line,1,19)); if(!$ts || $ts>=$cutoff) $kept[]=$line; } if(count($kept)!=count($log)) update_option('kcf_log',$kept,false); $log=$kept; } echo '<div class="wrap"><h1>Diagnostika</h1><form method="post" action="'.admin_url('admin-post.php?action=kcf_check_imap_now').'" style="margin-bottom:12px">'; wp_nonce_field('kcf_check_imap_now'); echo '<button class="button button-primary">Patikrinti IMAP dabar</button></form><form method="post" onsubmit="return confirm(\'Ištrinti visus logus?\')">'; wp_nonce_field('kcf_clear_logs'); echo '<button class="button" name="kcf_clear_logs" value="1">Ištrinti logus</button></form><h2>Paskutiniai logai</h2>'; if($log){ echo '<pre style="background:#fff;border:1px solid #ddd;padding:10px;max-height:420px;overflow:auto">'; foreach($log as $line){ echo esc_html($line)."\n"; } echo '</pre>'; } else { echo '<p>Logų nėra.</p>'; } echo '</div>'; }
?>
