
<?php if(!defined('ABSPATH')) exit;
add_action('admin_menu',function(){ add_menu_page('Kodra žinutės','Kodra žinutės','manage_options','kcf-messages','kcf_admin_messages_page','dashicons-email-alt2',26); add_submenu_page('kcf-messages','Nustatymai','Nustatymai','manage_options','kcf-settings','kcf_admin_settings_page'); add_submenu_page('kcf-messages','Diagnostika','Diagnostika','manage_options','kcf-diagnostics','kcf_admin_diagnostics_page'); });
add_action('admin_post_kcf_delete_message',function(){ if(!current_user_can('manage_options')) wp_die('Unauthorized'); check_admin_referer('kcf_delete_message'); global $wpdb; $id=intval($_GET['id']??0); if($id){ $wpdb->delete(KCF_TABLE,['id'=>$id]); $wpdb->delete(KCF_REPLIES_TABLE,['message_id'=>$id]); } wp_safe_redirect(admin_url('admin.php?page=kcf-messages&deleted=1')); exit; });
add_action('admin_post_kcf_reply_message',function(){ if(!current_user_can('manage_options')) wp_die('Unauthorized'); check_admin_referer('kcf_reply_message'); global $wpdb; $message_id=intval($_POST['message_id']); $row=$wpdb->get_row($wpdb->prepare('SELECT email FROM '.KCF_TABLE.' WHERE id=%d',$message_id)); $to=$row?$row->email:''; $subject=sanitize_text_field($_POST['subject']); $body=wp_kses_post($_POST['body']); $user_id=get_current_user_id(); $body_with_token=nl2br($body)."\n<!-- KCF-ID: ".$message_id." -->"; $headers=['Content-Type: text/html; charset=UTF-8','X-KCF-ID: '.$message_id]; $sent=wp_mail($to,$subject,$body_with_token,$headers); $wpdb->insert(KCF_REPLIES_TABLE,['message_id'=>$message_id,'created_at'=>current_time('mysql'),'wp_user_id'=>$user_id,'direction'=>0,'to_email'=>$to,'subject'=>$subject,'body'=>$body_with_token,'sent'=>$sent?1:0,'seen'=>0],['%d','%s','%d','%d','%s','%s','%s','%d','%d']); wp_safe_redirect(admin_url('admin.php?page=kcf-messages&view='.$message_id.'&replied='.($sent?'1':'0'))); exit; });
add_action('admin_post_kcf_check_imap_now',function(){ if(!current_user_can('manage_options')) wp_die('Unauthorized'); check_admin_referer('kcf_check_imap_now'); do_action('kcf_check_mail_event'); wp_safe_redirect(admin_url('admin.php?page=kcf-diagnostics')); exit; });
function kcf_mark_message_seen($id){ global $wpdb; $wpdb->update(KCF_TABLE,['seen'=>1],['id'=>$id]); $wpdb->query($wpdb->prepare('UPDATE '.KCF_REPLIES_TABLE.' SET seen=1 WHERE message_id=%d AND seen=0',$id)); }
function kcf_admin_messages_page(){ if(!current_user_can('manage_options')) return; global $wpdb; $table=KCF_TABLE; echo '<div class="wrap"><h1>Kodra žinutės</h1>';
  $q=sanitize_text_field($_GET['q']??''); echo '<form method="get" style="margin:8px 0 12px"><input type="hidden" name="page" value="kcf-messages"><input type="text" name="q" value="'.esc_attr($q).'" placeholder="Paieška (vardas, paštas, tel., įmonė)" style="min-width:340px;margin-right:6px"><button class="button button-primary">Ieškoti</button> <a class="button" href="'.admin_url('admin.php?page=kcf-messages').'">Išvalyti</a></form>';
  if(isset($_GET['view'])){ $id=intval($_GET['view']); $row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$table} WHERE id=%d",$id),ARRAY_A); echo '<h2>#'.intval($id).'</h2>'; if($row){ echo '<div class="kcf-two-col"><div class="kcf-col kcf-col-left"><h3>Pagrindinė informacija</h3><table class="widefat striped">'; foreach(['Vardas'=>$row['name'],'Telefonas'=>$row['phone'],'El. paštas'=>$row['email'],'Žinutė'=>$row['message']] as $l=>$v){ echo '<tr><th>'.esc_html($l).'</th><td>'.wp_kses_post(nl2br(esc_html((string)$v))).'</td></tr>'; } echo '</table></div><div class="kcf-col kcf-col-right"><h3>Kita</h3><table class="widefat striped">'; foreach(['Data'=>$row['created_at'],'Įmonė'=>$row['company'],'IP adresas'=>$row['ip'],'Naršyklė'=>$row['user_agent'],'Įrašo ID'=>$row['id']] as $l=>$v){ echo '<tr><th>'.esc_html($l).'</th><td>'.wp_kses_post(nl2br(esc_html((string)$v))).'</td></tr>'; } echo '</table></div></div>'; echo '<style>.kcf-two-col{display:grid;grid-template-columns:7fr 3fr;gap:18px;max-width:100%;width:100%}.kcf-two-col th{width:220px}.kcf-two-col th,.kcf-two-col td{word-break:break-word;overflow-wrap:anywhere}.kcf-thread-item.kcf-latest strong{font-weight:500}.kcf-unread-dot{display:inline-block;width:8px;height:8px;background:#d63638;border-radius:50%;margin-left:6px;vertical-align:middle}</style>';
    $delete_url=wp_nonce_url(admin_url('admin-post.php?action=kcf_delete_message&id='.$id),'kcf_delete_message'); echo '<p style="margin-top:12px"><a href="'.$delete_url.'" class="button button-danger kcf-del">Ištrinti</a> <a href="'.admin_url('admin.php?page=kcf-messages').'" class="button">Grįžti</a></p><script>document.addEventListener("click",e=>{if(e.target.classList.contains("kcf-del")&&!confirm("Ar tikrai ištrinti šią žinutę?")){e.preventDefault();}});</script>';
    echo '<hr><h2>Atsakymų gija</h2>'; $replies=$wpdb->get_results($wpdb->prepare("SELECT r.*, u.display_name FROM ".KCF_REPLIES_TABLE." r LEFT JOIN {$wpdb->users} u ON u.ID=r.wp_user_id WHERE r.message_id=%d ORDER BY r.id ASC",$id),ARRAY_A);
    if($replies){ $total=count($replies); $i=0; echo '<ul class="kcf-thread" id="kcf-thread">'; foreach($replies as $rep){ $i++; $by=intval($rep['direction'])===1?'Klientas':(!empty($rep['display_name'])?$rep['display_name']:'Admin'); $cls=intval($rep['seen'])===0?' kcf-unread-burst kcf-highlight':''; if($i===$total){ $cls+=' kcf-latest'; } $clean=function_exists('kcf_trim_body_for_admin')?kcf_trim_body_for_admin($rep['body']):$rep['body']; echo '<li class="kcf-thread-item'+$cls+'"><div><strong>'.esc_html($rep['subject']).'</strong></div><div><em>'.esc_html($rep['created_at']).'</em> — '.esc_html($by).'</div><div style="word-break:break-word">'.wp_kses_post(nl2br(esc_html($clean))).'</div></li>'; } echo '</ul><script>(function(){setTimeout(function(){document.querySelectorAll(".kcf-thread-item.kcf-highlight").forEach(function(el){el.classList.add("kcf-fade-end");});},60000);})();</script>'; } else { echo '<p>Gijoje dar nėra įrašų.</p>'; }
    $default_subject='Re: [KCF #'.$id.'] Atsakymas į Jūsų žinutę'; echo '<hr><h2>Atsakyti</h2><form method="post" action="'.admin_url('admin-post.php?action=kcf_reply_message').'" style="max-width:700px">'; wp_nonce_field('kcf_reply_message'); echo '<input type="hidden" name="message_id" value="'.intval($id).'"><input type="hidden" name="to" value=""><p><label>Tema: <input type="text" name="subject" value="'.esc_attr($default_subject).'" style="width:100%" required></label></p><p><label>Žinutė:<br><textarea name="body" rows="8" style="width:100%" required></textarea></label></p><p><button type="submit" class="button button-primary">Siųsti atsakymą</button></p></form>'; kcf_mark_message_seen($id);
  } else { echo '<p>Įrašas nerastas.</p>'; } echo '</div>'; return; }
  $where='WHERE 1=1'; $params=[]; if($q){ $like='%'.$wpdb->esc_like($q).'%'; $where+=' AND (name LIKE %s OR email LIKE %s OR phone LIKE %s OR company LIKE %s)'; $params=[$like,$like,$like,$like]; }
  $per=20; $paged=max(1,intval($_GET['paged']??1)); $off=($paged-1)*$per; $sql_total="SELECT COUNT(*) FROM {$table} $where"; $total=(int)($params? $wpdb->get_var($wpdb->prepare($sql_total,$params)) : $wpdb->get_var($sql_total));
  $sql_items="SELECT id,created_at,name,email,phone,company,LEFT(message,160) AS excerpt, seen FROM {$table} $where ORDER BY id DESC LIMIT %d OFFSET %d"; $args=$params; $args+=[ $per, $off ]; $items=$params? $wpdb->get_results($wpdb->prepare($sql_items,$args),ARRAY_A) : $wpdb->get_results($wpdb->prepare($sql_items,$per,$off),ARRAY_A);
  $base=admin_url('admin.php?page=kcf-messages'); echo '<table class="widefat striped" style="table-layout:fixed"><thead><tr><th style="width:60px">ID</th><th style="width:160px">Data</th><th style="width:140px">Vardas</th><th style="width:220px">El. paštas</th><th style="width:160px">Telefonas</th><th style="width:160px">Įmonė</th><th>Žinutė</th><th style="width:190px">Veiksmai</th></tr></thead><tbody>';
  if($items){ 
    foreach($items as $it){ $view=esc_url(add_query_arg(['view'=>$it['id']],$base)); $del=wp_nonce_url(admin_url('admin-post.php?action=kcf_delete_message&id='.$it['id']),'kcf_delete_message'); $row_cls=intval($it['seen'])===0?' style="background:#fff8e1"':''; $dot=intval($it['seen'])===0?' <span class="kcf-unread-dot" title="Neskaityta"></span>':''; echo '<tr'.$row_cls.'><td><a href="'.$view.'">'.intval($it['id']).'</a>'.$dot.'</td><td>'.esc_html($it['created_at']).'</td><td>'.esc_html($it['name']).'</td><td style="word-break:break-word"><a href="mailto:'.esc_attr($it['email']).'">'.esc_html($it['email']).'</a></td><td>'.esc_html($it['phone']).'</td><td>'.esc_html($it['company']).'</td><td style="word-break:break-word">'.esc_html($it['excerpt']).'</td><td><a href="'.$view.'" class="button">Peržiūrėti</a> <a href="'.$del.'" class="button kcf-del">Ištrinti</a></td></tr>'; }
  } else { echo '<tr><td colspan="8">Nėra įrašų.</td></tr>'; }
  echo '</tbody></table><script>document.addEventListener("click",e=>{if(e.target.classList.contains("kcf-del")&&!confirm("Ar tikrai ištrinti?")){e.preventDefault();}});</script>'; $pages=max(1,ceil($total/$per)); if($pages>1){ echo '<div class="tablenav"><div class="tablenav-pages">'+paginate_links({'base':$base+'%_%','format':'&paged=%#%','current':$paged,'total':$pages})+'</div></div>'; } echo '</div>'; }
function kcf_admin_diagnostics_page(){ if(!current_user_can('manage_options')) return; $ret_days=intval(kcf_settings_get('log_retention_days',30)); if(isset($_POST['kcf_clear_logs'])&&check_admin_referer('kcf_clear_logs')){ delete_option('kcf_log'); echo '<div class="updated"><p>Logai ištrinti.</p></div>'; } $log=get_option('kcf_log',[]); if($log){ $kept=[]; $cutoff=strtotime('-'.$ret_days.' days'); foreach($log as $line){ $ts=strtotime(substr($line,1,19)); if(!$ts || $ts>=$cutoff) $kept[]=$line; } if(count($kept)!=count($log)) update_option('kcf_log',$kept,false); $log=$kept; } echo '<div class="wrap"><h1>Diagnostika</h1><form method="post" action="'.admin_url('admin-post.php?action=kcf_check_imap_now').'" style="margin-bottom:12px">'; wp_nonce_field('kcf_check_imap_now'); echo '<button class="button button-primary">Patikrinti IMAP dabar</button></form><form method="post" onsubmit="return confirm(\'Ištrinti visus logus?\')">'; wp_nonce_field('kcf_clear_logs'); echo '<button class="button" name="kcf_clear_logs" value="1">Ištrinti logus</button></form><h2>Paskutiniai logai</h2>'; if($log){ echo '<pre style="background:#fff;border:1px solid #ddd;padding:10px;max-height:420px;overflow:auto">'; foreach($log as $line){ echo esc_html($line)."\n"; } echo '</pre>'; } else { echo '<p>Logų nėra.</p>'; } echo '</div>'; }
?>
