
<?php if(!defined('ABSPATH')) exit;
function kcf_admin_settings_page(){
  if(isset($_POST['kcf_save_settings']) && check_admin_referer('kcf_save_settings')){
    $opt=[ 'from_name'=>sanitize_text_field($_POST['from_name']??'Kodra'),'from_email'=>sanitize_email($_POST['from_email']??''),'smtp_enabled'=>!empty($_POST['smtp_enabled'])?1:0,'smtp_host'=>sanitize_text_field($_POST['smtp_host']??''),'smtp_port'=>intval($_POST['smtp_port']??587),'smtp_encrypt'=>in_array($_POST['smtp_encrypt']??'tls',['ssl','tls','none'])?$_POST['smtp_encrypt']:'tls','smtp_user'=>sanitize_text_field($_POST['smtp_user']??''),'smtp_pass'=>$_POST['smtp_pass']??'','imap_host'=>sanitize_text_field($_POST['imap_host']??''),'imap_port'=>intval($_POST['imap_port']??993),'imap_encrypt'=>in_array($_POST['imap_encrypt']??'ssl',['ssl','tls','none'])?$_POST['imap_encrypt']:'ssl','imap_user'=>sanitize_text_field($_POST['imap_user']??''),'imap_pass'=>$_POST['imap_pass']??'','imap_folder'=>sanitize_text_field($_POST['imap_folder']??'INBOX'),'recaptcha_enabled'=>!empty($_POST['recaptcha_enabled'])?1:0,'recaptcha_site_key'=>sanitize_text_field($_POST['recaptcha_site_key']??''),'recaptcha_secret_key'=>sanitize_text_field($_POST['recaptcha_secret_key']??''),'recaptcha_threshold'=>floatval($_POST['recaptcha_threshold']??0.5),'log_retention_days'=>intval($_POST['log_retention_days']??30) ];
    update_option(KCF_OPT,$opt); echo '<div class="updated"><p>Nustatymai išsaugoti.</p></div>';
  }
  $o=get_option(KCF_OPT,[]); $def=function($k,$d='')use($o){return isset($o[$k])?$o[$k]:$d;};
  echo '<div class="wrap"><h1>Kodra žinučių nustatymai</h1><form method="post">'; wp_nonce_field('kcf_save_settings');
  echo '<h2>Siuntimo „From“</h2><table class="form-table"><tr><th>From vardas</th><td><input type="text" class="regular-text" name="from_name" value="'.esc_attr($def('from_name','Kodra')).'"></td></tr><tr><th>From el. paštas</th><td><input type="email" class="regular-text" name="from_email" value="'.esc_attr($def('from_email','')).'"></td></tr></table>';
  echo '<h2>SMTP</h2><table class="form-table"><tr><th>Įjungti SMTP</th><td><label><input type="checkbox" name="smtp_enabled" value="1" '.checked($def('smtp_enabled',0),1,false).'> Naudoti SMTP</label></td></tr><tr><th>Host</th><td><input type="text" class="regular-text" name="smtp_host" value="'.esc_attr($def('smtp_host','')).'"></td></tr><tr><th>Port</th><td><input type="number" name="smtp_port" value="'.esc_attr($def('smtp_port',587)).'"></td></tr><tr><th>Šifravimas</th><td><select name="smtp_encrypt">'; $se=$def('smtp_encrypt','tls'); echo '<option value="ssl" '.selected($se,'ssl',false).'>SSL</option><option value="tls" '.selected($se,'tls',false).'>TLS</option><option value="none" '.selected($se,'none',false).'>Nėra</option></select></td></tr><tr><th>Vartotojas</th><td><input type="text" class="regular-text" name="smtp_user" value="'.esc_attr($def('smtp_user','')).'"></td></tr><tr><th>Slaptažodis</th><td><input type="password" class="regular-text" name="smtp_pass" value="'.esc_attr($def('smtp_pass','')).'"></td></tr></table>';
  echo '<h2>IMAP</h2><table class="form-table"><tr><th>Host</th><td><input type="text" class="regular-text" name="imap_host" value="'.esc_attr($def('imap_host','')).'"></td></tr><tr><th>Port</th><td><input type="number" name="imap_port" value="'.esc_attr($def('imap_port',993)).'"></td></tr><tr><th>Šifravimas</th><td><select name="imap_encrypt">'; $ie=$def('imap_encrypt','ssl'); echo '<option value="ssl" '.selected($ie,'ssl',false).'>SSL</option><option value="tls" '.selected($ie,'tls',false).'>TLS</option><option value="none" '.selected($ie,'none',false).'>Nėra</option></select></td></tr><tr><th>Vartotojas</th><td><input type="text" class="regular-text" name="imap_user" value="'.esc_attr($def('imap_user','')).'"></td></tr><tr><th>Slaptažodis</th><td><input type="password" class="regular-text" name="imap_pass" value="'.esc_attr($def('imap_pass','')).'"></td></tr><tr><th>Aplankas</th><td><input type="text" class="regular-text" name="imap_folder" value="'.esc_attr($def('imap_folder','INBOX')).'"></td></tr></table>';
  echo '<h2>reCAPTCHA v3</h2><table class="form-table"><tr><th>Įjungti reCAPTCHA v3</th><td><label><input type="checkbox" name="recaptcha_enabled" value="1" '.checked($def('recaptcha_enabled',0),1,false).'> Aktyvuoti</label></td></tr><tr><th>Site Key</th><td><input type="text" class="regular-text" name="recaptcha_site_key" value="'.esc_attr($def('recaptcha_site_key','')).'"></td></tr><tr><th>Secret Key</th><td><input type="text" class="regular-text" name="recaptcha_secret_key" value="'.esc_attr($def('recaptcha_secret_key','')).'"></td></tr><tr><th>Score slenkstis</th><td><input type="number" step="0.1" min="0" max="1" name="recaptcha_threshold" value="'.esc_attr($def('recaptcha_threshold',0.5)).'"></td></tr><tr><th>Diagnostikos logų saugojimas (dienomis)</th><td><input type="number" min="1" name="log_retention_days" value="'.esc_attr($def('log_retention_days',30)).'"></td></tr></table>';
  echo '<p><button class="button button-primary" name="kcf_save_settings" value="1">Išsaugoti</button></p></form></div>';
}
?>